import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  general: {
    flex: 1,
    width: "100%",
    height: "100%",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 50,
    borderRadius: 50,
    gap: 10,
    color: "white",
    backgroundColor: "white",
    flexShrink: 0,
  },
  Card: {
    width: 393,
    height: 370,
    marginTop: 10,
    // marginBottom: 2,
    marginLeft: 10,
    marginRight: 10,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderRadius: 10,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    // gap: 10,
  },
  Container: {
    weidth: 353,
    height: 632,
    padding: 10,
    // marginTop: 20,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
    flexDirection: "column",
    alignItems: "flex-start",
    alignSelf: "stretch",
    gap: 10,
    borderColor: "black",
    // borderWidth: 1,
  },

  Logo: {
    width: 333,
    height: 133,
    marginTop: 10,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "flex-start",
    // gap: 10,
    alignSelf: "stretch",
    borderBottomColor: "black",
    borderBottomWidth: 1.5,
  },
  buttonBlack: {
    flexDirection: "row",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 15,
    marginRight: 15,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    width: 120,
    height: 40,
    borderWidth: 1,
    backgroundColor: "black",
    borderRadius: 10,
  },
  buttonWhite: {
    flexDirection: "row",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 15,
    marginRight: 15,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    width: 120,
    height: 40,
    borderWidth: 1,
    backgroundColor: "white",
    borderRadius: 10,
  },
  textbuttonBlack: {
    font: 20,
    color: "white",
    marginRight: 5,
  },
  textbuttonWhite: {
    font: 20,
    color: "black",
    marginRight: 5,
  },
  textoLogo: {
    color: "#000",
    fontSize: 13,
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: 41,
    letterSpacing: 0.4,
  },
  textoLogoGrande: {
    alignSelf: "stretch",
    color: "#000",
    fontSize: 50,
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: 50,
    letterSpacing: 0.4,
  },
  CardForms: {
    width: 333,
    height: 231,
    marginLeft: 20,
    marginRight: 20,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "Flex-start",
    gap: 15,
    alignSelf: "stretch",
  },

  Bold: {
    color: "262526",
    textAlign: "center",
    fontSize: 13,
    fontStyle: "normal",
    fontWeight: "600",
    lineHeight: "normal",
  },

  BottomButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // gap: 20,
    marginTop: 20,
    marginBottom: 100,
    marginLeft: 20,
  },
  input: {
    borderColor: "262526",
    alignContent: "center",
    alignItems: "center",
    height: 42,
    width: 333,
    borderRadius: 5,
    borderWidth: 1,
  },
  miniCard: {
    backgroundColor: "white",
    width: 353,
    height: 333,
    marginTop: 50,
    marginBottom: 50,
    marginLeft: 20,
    marginRight: 20,
    borderRadius: 50,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
    borderColor: "black",
  },
  miniCardText: {
    color: " black",
    textAlign: "center",
    fontSize: 30,
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: 41,
    letterSpacing: 0.4,
  },
  modalBackground: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  profileImage: {
    width: 45,
    height: 45,
    borderRadius: 27,
  },
  Pasarela: {
    width: 333,
    height: 95,
    paddingTop: 10,
    paddingBottom: 10,
    marginTop: 10,
    marginBottom: 10,
    marginRight: 10,
    alignItems: "center",
    gap: 10,
    alignSelf: "stretch",
    borderColor: "black",
    // borderWidth: 1,
  },
  BoxesContainer: {
    flex: 3,
    width: 100,
    borderColor: "black",
    borderWidth: 1,
  },

  Card_reservas_ejemplo: {
    width: 370,
    height: 130,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    marginVertical: 20,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderRadius: 40,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    backgroundColor: "white",
    position: "relative",
    borderRightWidth: 2,
    borderRightColor: "black",
  },
  Card_reservas: {
    width: 393,
    height: 620,
    position: "relative",
    top: -100,
    marginTop: 1,
    marginLeft: 10,
    marginRight: 10,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderRadius: 10,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  logo_deep_foto: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: 333,
    height: 45,
    backgroundColor: "white",
    borderRadius: 10,
    position: "relative",
  },
  nombre_pag: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: 393,
    height: 70,
    top: -90,
    backgroundColor: "white",
    borderRadius: 10,
    position: "relative",
  },

  bottomBar: {
    //lA BARRA DE NAVEGACIÓN WAZAA
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    bottom: -70,
    height: 60,
    width: 393,
    backgroundColor: "white",
    borderTopColor: "#ccc",
    position: "absolute",
  },
  scrollContainer: {
    padding: 10,
  },
});

export default styles;
